# This workflow will build the etcd-operator and publish artifacts

name: CI

on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+'
      - 'master'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'release/v[0-9]+.[0-9]+'
      - 'master'

env:
  GITHUB_SHA: ${{ github.sha }}
#  GOOGLE_APPLICATION_CREDENTIALS: GOOGLE_APPLICATION_CREDENTIALS.json

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout Shared Actions
        uses: actions/checkout@v2
        with:
          repository: streamnative/actions-library
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: .github/actions
#
#      - name: Compute target metadata
#        id: target_meta
#        uses: ./.github/actions/target_metadata
#
#      - name: Compute Image Tag
#        id: image_meta
#        uses: ./.github/actions/image_metadata
#        with:
#          base_image: gcr.io/affable-ray-226821/streamnative/etcd-operator
#          target_env: ${{ steps.target_meta.outputs.target_env }}
#          tag_name: ${{ steps.target_meta.outputs.tag_name }}
#          release_version: ${{ steps.target_meta.outputs.release_version }}

      - name: Setup Initial Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '298.0.0'
          service_account_email: ${{ secrets.NEW_GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.NEW_GCP_SA_KEY }}
          export_default_credentials: true

      # NOTE! we use the "bootstrap" creds for this, as it has permissions
      # to push objects but the other accounts do not
      - name: Generate Access Token
        id: gcr_access_token
        run: |
          echo "::set-output name=token::$(gcloud auth print-access-token)"

      - name: Publish to gcr
        uses: docker/build-push-action@v1
        with:
          registry: gcr.io
          repository: affable-ray-226821/streamnative/etcd-operator
          username: oauth2accesstoken
          password: ${{ steps.gcr_access_token.outputs.token }}
#          tags: ${{ steps.image_meta.outputs.extra_tags }}
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
          build_args: REVISION=${{ github.sha }}
